version: '3'
services:
  elasticsearch:
    image: elasticsearch:2.4.6
    ports:
      - "9200:9200"
    environment:
      - cluster.name=logging-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:4.4
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    # Plugins (Timelion ya viene incluido en esta versión)

  app-node:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200